-- Durable crawl schedule. Apply manually in the Supabase SQL Editor.
CREATE TABLE IF NOT EXISTS public.crawl_targets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source TEXT NOT NULL,
    slug TEXT NOT NULL DEFAULT '',
    priority INT NOT NULL DEFAULT 1,
    interval_minutes INT NOT NULL DEFAULT 1440 CHECK (interval_minutes > 0),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('candidate', 'active', 'paused', 'dead')),
    next_run_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    lease_until TIMESTAMPTZ,
    last_attempt_at TIMESTAMPTZ,
    last_success_at TIMESTAMPTZ,
    consecutive_failures INT NOT NULL DEFAULT 0,
    consecutive_not_found INT NOT NULL DEFAULT 0,
    last_error TEXT,
    last_job_count INT,
    content_hash TEXT,
    hash_unchanged_streak INT NOT NULL DEFAULT 0,
    zero_job_streak INT NOT NULL DEFAULT 0,
    last_discovery_probe_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (source, slug)
);

CREATE INDEX IF NOT EXISTS crawl_targets_due_idx
    ON public.crawl_targets (status, next_run_at);
ALTER TABLE public.crawl_targets ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.crawl_targets FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.crawl_targets TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.crawl_targets_id_seq TO service_role;

-- Seed snapshot of app.crawlers.crawl_registry; safe to re-run.
INSERT INTO public.crawl_targets (source, slug, priority, interval_minutes, status) VALUES
    ('ycombinator', '', 1, 1440, 'active'),
    ('firecrawl', 'Razorpay|https://razorpay.com/jobs/', 0, 1440, 'active'),
    ('firecrawl', 'PhonePe|https://www.phonepe.com/careers/job-openings/', 0, 1440, 'active'),
    ('firecrawl', 'CRED|https://careers.cred.club/', 0, 1440, 'active'),
    ('firecrawl', 'Zerodha|https://zerodha.com/careers', 0, 1440, 'active'),
    ('firecrawl', 'Swiggy|https://careers.swiggy.com', 1, 1440, 'active'),
    ('firecrawl', 'BrowserStack|https://www.browserstack.com/careers', 1, 1440, 'active'),
    ('firecrawl', 'PostHog|https://posthog.com/careers', 1, 1440, 'active'),
    ('firecrawl', 'Linear|https://linear.app/careers', 1, 1440, 'active'),
    ('ashby', 'notion', 0, 1440, 'active'),
    ('ashby', 'openai', 0, 1440, 'active'),
    ('ashby', 'elevenlabs', 0, 1440, 'active'),
    ('ashby', 'cursor', 0, 1440, 'active'),
    ('ashby', 'cognition', 0, 1440, 'active'),
    ('ashby', 'perplexity', 0, 1440, 'active'),
    ('greenhouse', 'stripe', 0, 1440, 'active'),
    ('greenhouse', 'databricks', 0, 1440, 'active'),
    ('greenhouse', 'mongodb', 0, 1440, 'active'),
    ('greenhouse', 'okta', 0, 1440, 'active'),
    ('greenhouse', 'zscaler', 0, 1440, 'active'),
    ('greenhouse', 'inmobi', 0, 1440, 'active'),
    ('greenhouse', 'gitlab', 0, 1440, 'active'),
    ('greenhouse', 'rubrik', 0, 1440, 'active'),
    ('greenhouse', 'elastic', 0, 1440, 'active'),
    ('greenhouse', 'druva', 0, 1440, 'active'),
    ('greenhouse', 'twilio', 0, 1440, 'active'),
    ('greenhouse', 'fivetran', 0, 1440, 'active'),
    ('greenhouse', 'coinbase', 0, 1440, 'active'),
    ('greenhouse', 'samsara', 0, 1440, 'active'),
    ('greenhouse', 'airbnb', 0, 1440, 'active'),
    ('greenhouse', 'datadog', 0, 1440, 'active'),
    ('greenhouse', 'groww', 0, 1440, 'active'),
    ('greenhouse', 'postman', 0, 1440, 'active'),
    ('lever', 'paytm', 0, 1440, 'active'),
    ('lever', 'cred', 0, 1440, 'active'),
    ('lever', 'coupa', 0, 1440, 'active'),
    ('smartrecruiters', 'servicenow', 0, 1440, 'active'),
    ('ashby', 'ramp', 1, 1440, 'active'),
    ('ashby', 'linear', 1, 1440, 'active'),
    ('ashby', 'sentry', 1, 1440, 'active'),
    ('ashby', 'vanta', 1, 1440, 'active'),
    ('ashby', 'synthesia', 1, 1440, 'active'),
    ('ashby', 'hex', 1, 1440, 'active'),
    ('ashby', 'modal', 1, 1440, 'active'),
    ('ashby', 'posthog', 1, 1440, 'active'),
    ('ashby', 'render', 1, 1440, 'active'),
    ('ashby', 'cohere', 1, 1440, 'active'),
    ('ashby', 'replit', 1, 1440, 'active'),
    ('ashby', 'deepgram', 1, 1440, 'active'),
    ('ashby', 'supabase', 1, 1440, 'active'),
    ('ashby', 'langchain', 1, 1440, 'active'),
    ('ashby', 'baseten', 1, 1440, 'active'),
    ('greenhouse', 'figma', 1, 1440, 'active'),
    ('greenhouse', 'cloudflare', 1, 1440, 'active'),
    ('greenhouse', 'yugabyte', 1, 1440, 'active'),
    ('greenhouse', 'cockroachlabs', 1, 1440, 'active'),
    ('greenhouse', 'pingidentity', 1, 1440, 'active'),
    ('greenhouse', 'amplitude', 1, 1440, 'active'),
    ('greenhouse', 'mixpanel', 1, 1440, 'active'),
    ('greenhouse', 'starburst', 1, 1440, 'active'),
    ('greenhouse', 'gusto', 1, 1440, 'active'),
    ('greenhouse', 'instacart', 1, 1440, 'active'),
    ('greenhouse', 'affirm', 1, 1440, 'active'),
    ('greenhouse', 'discord', 1, 1440, 'active'),
    ('greenhouse', 'robinhood', 1, 1440, 'active'),
    ('greenhouse', 'brex', 1, 1440, 'active'),
    ('greenhouse', 'chime', 1, 1440, 'active'),
    ('greenhouse', 'lyft', 1, 1440, 'active'),
    ('greenhouse', 'pinterest', 1, 1440, 'active'),
    ('greenhouse', 'reddit', 1, 1440, 'active'),
    ('greenhouse', 'pagerduty', 1, 1440, 'active'),
    ('greenhouse', 'qualtrics', 1, 1440, 'active'),
    ('greenhouse', 'checkr', 1, 1440, 'active'),
    ('greenhouse', 'carta', 1, 1440, 'active'),
    ('greenhouse', 'braze', 1, 1440, 'active'),
    ('greenhouse', 'confluent', 1, 1440, 'active'),
    ('greenhouse', 'snowflake', 1, 1440, 'active'),
    ('greenhouse', 'paloaltonetworks', 1, 1440, 'active'),
    ('greenhouse', 'crowdstrike', 1, 1440, 'active'),
    ('greenhouse', 'splunk', 1, 1440, 'active'),
    ('greenhouse', 'box', 1, 1440, 'active'),
    ('lever', 'pocketfm', 1, 1440, 'active'),
    ('lever', 'outreach', 1, 1440, 'active'),
    ('lever', 'palantir', 1, 1440, 'active'),
    ('lever', 'spotify', 1, 1440, 'active'),
    ('ashby', 'anyscale', 2, 1440, 'active'),
    ('ashby', 'pinecone', 2, 1440, 'active'),
    ('ashby', 'resend', 2, 1440, 'active'),
    ('ashby', 'tavily', 2, 1440, 'active'),
    ('ashby', 'e2b', 2, 1440, 'active'),
    ('ashby', 'warp', 2, 1440, 'active'),
    ('ashby', 'graphite', 2, 1440, 'active'),
    ('ashby', 'railway', 2, 1440, 'active'),
    ('ashby', 'suno', 2, 1440, 'active'),
    ('greenhouse', 'lattice', 2, 1440, 'active'),
    ('greenhouse', 'dremio', 2, 1440, 'active'),
    ('greenhouse', 'slice', 2, 1440, 'active'),
    ('greenhouse', 'porter', 2, 1440, 'active'),
    ('ashby', 'fly', 2, 1440, 'active'),
    ('ashby', 'sourcegraph', 2, 1440, 'active'),
    ('ashby', 'midjourney', 2, 1440, 'active'),
    ('lever', 'wealthfront', 2, 1440, 'active'),
    ('smartrecruiters', 'averydennison', 2, 1440, 'active'),
    ('adzuna', 'software engineer', 0, 1440, 'active'),
    ('jobspy', 'data analyst India', 2, 1440, 'active')
ON CONFLICT (source, slug) DO NOTHING;

CREATE OR REPLACE FUNCTION public.claim_due_crawl_targets(p_limit INT, p_lease_seconds INT)
RETURNS SETOF public.crawl_targets
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $$
    WITH due AS (
        SELECT id FROM public.crawl_targets
        WHERE status = 'active' AND next_run_at <= now()
          AND (lease_until IS NULL OR lease_until <= now())
        ORDER BY priority ASC, next_run_at ASC
        FOR UPDATE SKIP LOCKED
        LIMIT GREATEST(1, p_limit)
    )
    UPDATE public.crawl_targets AS target
    SET lease_until = now() + make_interval(secs => GREATEST(1, p_lease_seconds)),
        last_attempt_at = now(), updated_at = now()
    FROM due WHERE target.id = due.id
    RETURNING target.*;
$$;
REVOKE ALL ON FUNCTION public.claim_due_crawl_targets(INT, INT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_due_crawl_targets(INT, INT) TO service_role;

CREATE OR REPLACE FUNCTION public.complete_crawl_target(
    p_source TEXT, p_slug TEXT, p_success BOOLEAN, p_interval_minutes INT,
    p_job_count INT DEFAULT 0, p_content_hash TEXT DEFAULT NULL,
    p_error TEXT DEFAULT NULL, p_not_found BOOLEAN DEFAULT FALSE,
    p_min_interval_minutes INT DEFAULT 360,
    p_max_interval_minutes INT DEFAULT 2880,
    p_dead_after_failures INT DEFAULT 10
) RETURNS VOID
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
    row_target public.crawl_targets%ROWTYPE;
    next_interval INT;
    next_failures INT;
    unchanged INT;
    empty_streak INT;
BEGIN
    SELECT * INTO row_target FROM public.crawl_targets
    WHERE source = p_source AND slug = p_slug FOR UPDATE;
    IF NOT FOUND THEN RETURN; END IF;

    IF p_success THEN
        unchanged := CASE WHEN p_content_hash IS NOT NULL AND p_content_hash = row_target.content_hash
                          THEN row_target.hash_unchanged_streak + 1 ELSE 0 END;
        empty_streak := CASE WHEN COALESCE(p_job_count, 0) = 0
                             THEN row_target.zero_job_streak + 1 ELSE 0 END;
        next_interval := LEAST(p_max_interval_minutes, GREATEST(p_min_interval_minutes, p_interval_minutes));
        IF empty_streak >= 3 THEN next_interval := p_max_interval_minutes; END IF;
        IF row_target.priority = 0 THEN next_interval := LEAST(next_interval, 1440); END IF;
        UPDATE public.crawl_targets SET
            last_success_at = now(), consecutive_failures = 0, consecutive_not_found = 0,
            last_error = NULL, last_job_count = p_job_count,
            hash_unchanged_streak = unchanged,
            zero_job_streak = empty_streak,
            content_hash = COALESCE(p_content_hash, content_hash),
            interval_minutes = next_interval,
            next_run_at = now() + make_interval(mins => next_interval),
            lease_until = NULL, updated_at = now()
        WHERE id = row_target.id;
    ELSE
        next_failures := row_target.consecutive_failures + 1;
        UPDATE public.crawl_targets SET
            consecutive_failures = next_failures,
            consecutive_not_found = CASE WHEN p_not_found THEN consecutive_not_found + 1 ELSE 0 END,
            last_error = left(COALESCE(p_error, 'crawl failed'), 1000),
            status = CASE WHEN next_failures >= GREATEST(1, p_dead_after_failures)
                               OR (p_not_found AND row_target.consecutive_not_found + 1 >= 3)
                          THEN 'dead' ELSE status END,
            next_run_at = now() + make_interval(secs => LEAST(86400,
                GREATEST(60, p_interval_minutes * 60 * power(2, LEAST(next_failures, 10)))
                * (0.9 + random() * 0.2))),
            lease_until = NULL, updated_at = now()
        WHERE id = row_target.id;
    END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.complete_crawl_target(TEXT, TEXT, BOOLEAN, INT, INT, TEXT, TEXT, BOOLEAN, INT, INT, INT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.complete_crawl_target(TEXT, TEXT, BOOLEAN, INT, INT, TEXT, TEXT, BOOLEAN, INT, INT, INT) TO service_role;

ALTER TABLE public.jobs ADD COLUMN IF NOT EXISTS missed_crawls SMALLINT NOT NULL DEFAULT 0;

CREATE OR REPLACE FUNCTION public.reset_job_missed_crawls()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
    IF TG_OP = 'INSERT' OR NEW.last_seen_at IS DISTINCT FROM OLD.last_seen_at THEN
        NEW.missed_crawls := 0;
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS jobs_reset_missed_crawls ON public.jobs;
CREATE TRIGGER jobs_reset_missed_crawls
    BEFORE INSERT OR UPDATE ON public.jobs
    FOR EACH ROW EXECUTE FUNCTION public.reset_job_missed_crawls();

CREATE OR REPLACE FUNCTION public.deactivate_unseen_jobs_batch(
    p_source TEXT, p_company TEXT, p_careers_url TEXT, p_since TIMESTAMPTZ, p_threshold SMALLINT
) RETURNS INT
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE changed INT;
BEGIN
    WITH marked AS (
        UPDATE public.jobs SET missed_crawls = missed_crawls + 1,
            is_active = CASE WHEN missed_crawls + 1 >= GREATEST(1, p_threshold) THEN FALSE ELSE is_active END
        WHERE is_active = TRUE AND source_platform = p_source
          AND (p_company IS NULL OR company = p_company)
          AND (p_careers_url IS NULL OR careers_url = p_careers_url)
          AND last_seen_at IS NOT NULL AND last_seen_at < p_since
        RETURNING is_active
    )
    SELECT count(*) FILTER (WHERE NOT is_active) INTO changed FROM marked;
    RETURN changed;
END;
$$;
REVOKE ALL ON FUNCTION public.deactivate_unseen_jobs_batch(TEXT, TEXT, TEXT, TIMESTAMPTZ, SMALLINT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.deactivate_unseen_jobs_batch(TEXT, TEXT, TEXT, TIMESTAMPTZ, SMALLINT) TO service_role;
